CREATE TABLE IF NOT EXISTS pokemon (
    idPokemon INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    corPredominante VARCHAR(50) NOT NULL,
    habitat VARCHAR(100) NOT NULL,
    faseEvolucao VARCHAR(30) NOT NULL,
    geracao INT NOT NULL
);

CREATE TABLE IF NOT EXISTS tipo (
    idTipo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    nome VARCHAR(50) NULL,
    forteContra VARCHAR(45) NULL,
    fracoContra VARCHAR(45) NULL
);

INSERT INTO tipo (nome, forteContra, fracoContra) VALUES
    ('Normal', NULL, 'Luta'),
    ('Fogo', 'Planta', 'Água'),
    ('Água', 'Fogo', 'Elétrico'),
    ('Planta', 'Água', 'Fogo'),
    ('Elétrico', 'Água', 'Terrestre'),
    ('Gelo', 'Dragão', 'Fogo'),
    ('Luta', 'Normal', 'Psíquico'),
    ('Veneno', 'Fada', 'Psíquico'),
    ('Terrestre', 'Elétrico', 'Água'),
    ('Voador', 'Luta', 'Elétrico'),
    ('Psíquico', 'Luta', 'Sombrio'),
    ('Inseto', 'Psíquico', 'Fogo'),
    ('Pedra', 'Voador', 'Água'),
    ('Fantasma', 'Psíquico', 'Sombrio'),
    ('Dragão', 'Dragão', 'Fada'),
    ('Sombrio', 'Psíquico', 'Fada'),
    ('Metal', 'Fada', 'Fogo'),
    ('Fada', 'Dragão', 'Veneno');

CREATE TABLE pokemonTipo (
    idPokemon INT NOT NULL,
    idTipo INT NOT NULL,
    PRIMARY KEY (idPokemon, idTipo),
    FOREIGN KEY (idPokemon)
      REFERENCES pokemon(idPokemon),
    FOREIGN KEY (idTipo)
      REFERENCES tipo(idTipo)
);